name: Deploy Vite App to S3

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Determine environment and rename env file
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            cp .env.production .env
          else
            cp .env.development .env
          fi

      - name: Build the project
        run: npm run build:dev
        env:
          NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

      - name: Extract platform, environment folder, and CloudFront ID
        id: vars
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          PLATFORM=$(echo "$REPO_NAME" | sed 's/-client$//')

          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            ENV_FOLDER="prod"
            CLOUDFRONT_ID="${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }}"
          else
            ENV_FOLDER="dev"
            CLOUDFRONT_ID="${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}"
          fi

          S3_PATH="$PLATFORM/$ENV_FOLDER"

          echo "platform=$PLATFORM" >> $GITHUB_OUTPUT
          echo "env_folder=$ENV_FOLDER" >> $GITHUB_OUTPUT
          echo "s3_path=$S3_PATH" >> $GITHUB_OUTPUT
          echo "cloudfront_id=$CLOUDFRONT_ID" >> $GITHUB_OUTPUT

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: dist
          DEST_DIR: ${{ steps.vars.outputs.s3_path }}

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DISTRIBUTION: ${{ steps.vars.outputs.cloudfront_id }}
          PATHS: '/*'
