name: Deploy Vite App to S3

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build:dev

      - name: Extract platform and environment folder
        id: vars
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"        # e.g. hire-client
          PLATFORM=$(echo "$REPO_NAME" | sed 's/-client$//')  # e.g. hire

          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            ENV_FOLDER="prod"
          else
            ENV_FOLDER="dev"
          fi

          S3_PATH="$PLATFORM/$ENV_FOLDER"

          echo "platform=$PLATFORM" >> $GITHUB_OUTPUT
          echo "env_folder=$ENV_FOLDER" >> $GITHUB_OUTPUT
          echo "s3_path=$S3_PATH" >> $GITHUB_OUTPUT

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: dist
          DEST_DIR: ${{ steps.vars.outputs.s3_path }}
